提供清理接口和支持继承
aitsuki/SwipeMenuRecyclerView pull request #34
Opened 2023-04-14 07:55 UTC by nickming

1. 支持外部继承SwipeMenuRecyclerView,项目可能有自定义的RecyclerView或者需要埋点等自定义需求https://github.com/aitsuki/SwipeMenuRecyclerView/commit/8af232d691e33165aa3b4cf219157615bbfdbcb3
2. 支持清空listener,存在item绑定时导致重复绑定，可以先clear再添加https://github.com/aitsuki/SwipeMenuRecyclerView/commit/37aca94d10cafed50dce101919066fb2ed1fe031

2023-04-14 10:15 UTC, aitsuki requested changes

2023-04-14 10:15 UTC, aitsuki commented on library/src/main/java/com/aitsuki/swipe/SwipeLayout.kt
> +    fun clearListener() {
感谢支持，可以将名字改成clearListeners复数形式再次提交吗

2023-04-19 07:01 UTC, nickming commented on library/src/main/java/com/aitsuki/swipe/SwipeLayout.kt
> +    fun clearListener() {
好的

2023-04-19 07:16 UTC, nickming commented on library/src/main/java/com/aitsuki/swipe/SwipeLayout.kt
> +    fun clearListener() {
done

2023-04-19 11:00 UTC, aitsuki approved these changes

2023-04-19 11:00 UTC, merged